# -*- coding: utf-8 -*-
"""Gizem_Session#3_Homework Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yZ_8tzv_WhMpDTHIGKLOA373Ah1csXE-

# Python Session #3: Data Summary / Satistics - Homework Assignment

## Lecture Structure:

1. Measure of central tendency

- Mean
- Median
- Mode

2. Measure of spread

- Range
- Standard Deviation
- Variance

3. Correlation coeffcient

## We will use:
- `statistics.mean()`,
`statistics.median()`,
`statistics.mean()`,
`groupby.mean()`,
`groupby.median()`,
`gmean()`,
`statistics.stdev()`,
`statistics.variance()`,
`corr()`,
`numpy.corrcoef()`
"""

### Importing libraries and packages
import pandas as pd
import numpy as np
import statistics as st
import seaborn as sns
import matplotlib.pyplot as plt

### Reading data

cars = pd.read_csv("https://raw.githubusercontent.com/juliandnl/redi_ss20/master/cars.csv")  # cars dataset
olist = pd.read_csv("https://raw.githubusercontent.com/Kartthik-Rathinakumar/ReDI/main/Olist.csv")  # Olist - new dataset
rentals = pd.read_csv("https://raw.githubusercontent.com/juliandnl/redi_ss20/master/berlin_rental.csv")

"""
## **Question #1 : Rentals dataset**

For the rentals dataset, identify:

1. Dependent variable

2. Indpendent variable(s)

3. Statistically prove their relation, use the help of visual diagram whenever necessary."""

### Answer #1.1

### Answer #1.2

### Answer #1.3

"""## **Question #2 : rentals dataset**

Identify the best region to live, based on:

1. Average Price

2. Average Rooms Available

3. Average Space

4. What type of apartment condition is mostly available in Mitte, Kruezberg and Wilmersforf respectively?
"""

### Identify the best region to live, based on: Average Price

### Identify the best region to live, based on: Average Rooms Available

### Identify the best region to live, based on: Average Space

### What type of apartment condition is mostly available in Mitte, Kruezberg and Wedding respectively?

"""## **Question #3 : rentals dataset**

1. In what location are both the mean and median are same in terms of apartment Space?
2. Identify the location where the apartment rent variation is the highest
3. What is the average price of 2 room apartment in Mitte?
"""

### In what location are both the mean and median are same in terms of apartment Space?

### Identify the location where the apartment rent variation is very the highest

### What is the average price of 2 room apartment in Mitte?
rentals[(rentals["Region"] == "Mitte")]

"""## **Question #4 : Apartments dataset**

Identify an outlier from the Apartments dataset. Statistically show the difference in central tendency with and without those outliers.

**Hint**

Identify the outliers visually with a plot.
"""

#Answer
rentals.Rent.hist()

"""## **EXTRA MATERIAL**

**Using groupby with different functions for different columns**

The `.agg()` method also allows you to apply different functions to different columns. It's done by using a dictionary where the columns selected are the keys, and the functions you want to apply to each columns are the values. There is no need to select the columns before applying `.agg()` in this case, as the columns are selected inside the dictionary.

**Useful aggregation functions:**
- `mean()`
- `median()`
- `var()`
- `std()`
- `min()`
- `max()`
- `count()`
- `sum()`
- `nunique()`

**Bonus question #1:**

Revisit the `describe()` method from session #1. Study the output of the describe method, draw a simple barplot or any visual diagram for the dataset and check your understanding about the dataset.
"""

### Bonus question #1:
rentals.describe()

rentals.hist()



"""**Bonus question #2:**

Below mentioned are the points for 2 teams who participated in a Premiere league football batch. When a team wins a match, they get **3** points, if they lose the match then they get **0** points and if the match is draw then they get **1** point.

Study the data and share your understanding, mainly

According to you, Which team has performed better, why?

Team A : { 3,1,3,1,3,1,0,1,0,1,0,0,1,3,3,1,1,3,1,0 }

Team B : { 3,1,3,1,3,0,0,0,0,0,0,0,1,3,3,1,1,3,1,3 }
"""

### Bonus question #2:

"""**Bonus question #3:**

Based on the available cars data, Check whether the below hypothesis are valid.


1) If the doors are more, then the price of the car is high

2) If the price of the car is high, then the usage of the car is high ( Kms)

"""

### Bonus question #3:
cars.corr()

#answer to Bonus question 3:
#  1) not really, they have a very small negative correlation
#  2) again like the firts question they have a small negative correlation, so both of the hzpothesis are not valid.